### ISSUE TITLE
Test all transpiler patches

### ISSUE THREAD

**Issue by NoImageAvailable** [NoImageAvailable/CombatExtended#546]
Since transpiler patches have a tendency to fail silently need to manually test to make sure they work correctly.

List of all (tested) transpiler patches:
- [x] **[BROKEN]** PawnColumnWorkers_Resize: replaces UI constants to bring the outfit/etc. tabs in line with loadout
- [x] **[FIXED #566]** FloatMenuMakerMap.AddHumanlikeOrders(): adds additional float menu options (such as pick up). Modifies ForceWear option to add a weight/bulk check
- [x] **[FIXED #564]** DamageWorker_AddInjury.ApplyDamageToPart(): replaces call to vanilla armor system with our own
- [x] **[FIXED #565]** JobDriver_Wait.CheckForAutoAttack(): adds a CE-relevant check to targeting
- [x] **[WORKING]** JobGiver_UnloadYourInventory.TryGiveJob(): prevents vanilla job from unloading loadout inventory\*
- [x] **[WORKING]** VerbTracker.VerbsTick(): inserts a call to VerbCE.VerbTickCE() after the regular VerbTick
- [x] **[WORKING]** HediffComp_TendDuration.CompTended(): replaces a clamped value with our own
- [x] **[WORKING]** ThingListGroupHelper.Includes(): reroutes a method call to our own method to circumvent shell-related hardcoding
- [x] **[WORKING]** LordToil_Siege.LordToilTick(): reroutes a method call to our own method to circumvent shell-related hardcoding
- [x] **[WORKING]** Verb.TryStartCastOn(): adds a reload check when trying to shoot something (should reload before warmup sequence)
- [x] **[WORKING]** Fire.DoFireDamage(): replaces fire damage value 150 -> 300
- [x] **[WORKING]** TradeDeal.UpdateCurrencyCount(): reroutes method call to adjust trade price rounding (fixes an issue with bullet prices)
- [x] **[WORKING]** GenRadial.RadialPatternCount(): suppresses an error with CE ranges by extending radial range beyond 60 tiles
- [x] **[WORKING]** Pawn_HealthTracker.CheckForStateChange(): disables RNG death on downed
- [x] **[OBSOLETE]** RaidStrategyWorker_ImmediateAttackSappers.CanUseWith(): enables sapper raids for tribals\**
- [x] **[OBSOLETE]** HediffComp_GetsPermanent.CompPostInjuryHeal(): replaces a clamped value in vanilla with our own range\***

\* This might be better handled by disabling vanilla functionality and letting loadout logic take care of dumping unwanted inventory.
\** Probably obsolete now
\*** Unclear what original purpose was, possibly obsolete

**Comment by Alicecomma** [comment]
- [ ] Guns do not recognize ammo in the wearer inventory. Lead: Comp_AmmoUser and its AmmoList.
- [ ] Right-clicking ammo doesn't show "Pick up ammo" anymore like it used to - broken transpiler supposedly.

**Comment by DoomOfMax97** [comment]
It might be possible to write something on the console if the patch was successful, it makes verifying easier. Where do I find the patches?

**Comment by NoImageAvailable** [comment]
They're all in the Harmony folder

**Comment by Alicecomma** [comment]
ToolTipUtility, when mousing over a target for the first time with a pawn with the Bolt Action Rifle selected

```
Could not resolve symbol "1_labelShort" for string "Shot by {1_labelShort}".
Verse.Log:Error(String, Boolean)
Verse.Log:ErrorOnce(String, Int32, Boolean)
Verse.GrammarResolverSimple:Formatted(String, List`1, List`1)
Verse.GrammarResolverSimpleStringExtensions:Formatted(String, NamedArgument)
Verse.TranslatorFormattedStringExtensions:Translate(String, NamedArgument)
CombatExtended.Harmony.Harmony_TooltipUtility_ShotCalculationTipString_Patch:Postfix(String&, Thing)
Verse.TooltipUtility:ShotCalculationTipString_Patch1(Thing)
Verse.TooltipGiverList:DispenseAllThingTooltips()
RimWorld.MapInterface:MapInterfaceOnGUI_BeforeMainTabs()
RimWorld.UIRoot_Play:UIRootOnGUI()
Verse.Root:OnGUI()
```

**Comment by NoImageAvailable** [comment]
That one was already fixed in #566

**Comment by Alicecomma** [comment]
When using Dev mode explosion in an area with downed pawns, the following error occured, mentioning another transpiler

```
Explosion could not affect cell (110, 0, 136): System.ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
at System.Collections.Generic.List`1<RimWorld.Apparel>.get_Item (int) <0x00083>
at CombatExtended.ArmorUtilityCE.GetAfterArmorDamage (Verse.DamageInfo,Verse.Pawn,Verse.BodyPartRecord,bool&,bool&,bool&) <0x00b82>
at CombatExtended.Harmony.Harmony_DamageWorker_AddInjury_ApplyDamageToPart.ArmorReroute (Verse.Pawn,Verse.DamageInfo&,bool&,bool&) <0x000c9>
at (wrapper dynamic-method) Verse.DamageWorker_AddInjury.ApplyDamageToPart_Patch1 (object,Verse.DamageInfo,Verse.Pawn,Verse.DamageWorker/DamageResult) <0x00127>
at Verse.DamageWorker_AddInjury.ApplyToPawn (Verse.DamageInfo,Verse.Pawn) <0x002bb>
at Verse.DamageWorker_AddInjury.Apply (Verse.DamageInfo,Verse.Thing) <0x000be>
at Verse.Thing.TakeDamage (Verse.DamageInfo) <0x002dd>
at Verse.DamageWorker.ExplosionDamageThing (Verse.Explosion,Verse.Thing,System.Collections.Generic.List`1<Verse.Thing>,Verse.IntVec3) <0x00558>
at Verse.DamageWorker.ExplosionAffectCell (Verse.Explosion,Verse.IntVec3,System.Collections.Generic.List`1<Verse.Thing>,bool) <0x005c6>
at Verse.Explosion.AffectCell (Verse.IntVec3) <0x0019a>
at Verse.Explosion.Tick () <0x00156>
```

**Comment by JonnyNova** [comment]
I'm about half done with the PawnColumnWorkers_Resize patch. Should be done with it tomorrow

**Comment by NoImageAvailable** [comment]
PawnColumnWorkers patch finally finished https://github.com/NoImageAvailable/CombatExtended/commit/1e432981a491f92b7a576dc79b0c7c28f4b9bd11
